README.rst
=> read the docs introdução

README.rst
=> textos read the docs - funcionalidades

docs/10-validade_juridica.rst
=> textos read the docs - validade juridica

docs/20-contratos.rst
=> textos read the docs - contratos

docs/20-contratos.rst
=> textos read the docs - contratos nota

docs/21-registro.rst
=> textos read the docs - bitregistro

docs/21-registro.rst
=> textos read the docs - bitregistro registro unitario

docs/21-registro.rst
=> texto read the docs bitregistro unitario

docs/21-registro.rst
=> textos read the docs - criando o bitregistro

docs/21-registro.rst
=> text read the docs - textto certificado

docs/60-blockchains.rst
=> textos read the docs -assinatura digital

docs/60-blockchains.rst
=> textos read the docs - assinatura digital certificação

docs/60-blockchains.rst
=> textos read the docs - decred

docs/60-blockchains.rst
=> textos read the docs - decred blockchain

docs/60-blockchains.rst
=> textos read the docs - curiosidades

docs/80-recomendacoes.rst
=> textos read the docs - quando fazer seu bitregistro

docs/80-recomendacoes.rst
=> texto read the docs - o que registrar

docs/80-recomendacoes.rst
=> textos read the docs - como funciona

docs/80-recomendacoes.rst
=> textos read the docs - é seguro

docs/90-perguntas_frequentes.rst
=> textos read the docs - a justiça reconhece

docs/90-perguntas_frequentes.rst
=> textos read the docs - inpi

docs/90-perguntas_frequentes.rst
=> text read the docs - engano

docs/90-perguntas_frequentes.rst
=> textos read the docs - certifiquei meu contrato

docs/90-perguntas_frequentes.rst
=> textos read the docs - depois de certificar

docs/90-perguntas_frequentes.rst
=> textos read the docs - reconhecimento de firma

docs/90-perguntas_frequentes.rst
=> textos read the docs - documento ideal

docs/90-perguntas_frequentes.rst
=> textos read the docs - aceito nos tribunais

docs/90-perguntas_frequentes.rst
=> textos read the docs - ideia incrivel

docs/90-perguntas_frequentes.rst
=> textos read the docs - proteger ideia

docs/91-termos_de_uso.rst
Alterações e atualização da Política de Privacidade
=> Atualização da Política de Privacidade
